"""
AI Manga Studio V3.5 — Prompt Engine

Refactored from V3.0 single JSON field to 7-dimension independent structure.
Each dimension is generated by a dedicated AI Engine module.

Architecture: V3.5 7-Dimensional Prompt
    character_prompt   ← CharacterReasoner
    scene_prompt       ← SceneReasoner
    camera_prompt      ← CameraPlanner
    emotion_prompt     ← DialogueOptimizer
    motion_prompt      ← MotionPlanner
    lighting_prompt    ← (rule-based)
    negative_prompt    ← (default + project config)

Backward compatible with V3.0 PromptResult via to_legacy().
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


# ============================================================
# V3.5 Core Data Class
# ============================================================

@dataclass
class PromptV35:
    """7-dimensional independent prompt structure for V3.5.

    Each field is populated by its corresponding engine module.
    The synthesis methods produce the final Flux/Wan prompts.
    """

    # ── 7 Independent Dimensions ──────────────────────────

    character_prompt: str = ""
    """Character description, generated by CharacterReasoner."""

    scene_prompt: str = ""
    """Scene description, generated by SceneReasoner."""

    camera_prompt: str = ""
    """Camera movement description, generated by CameraPlanner."""

    emotion_prompt: str = ""
    """Emotion description, generated by DialogueOptimizer."""

    motion_prompt: str = ""
    """Motion/action description, generated by MotionPlanner."""

    lighting_prompt: str = ""
    """Lighting and shadow description, rule-based."""

    negative_prompt: str = ""
    """Negative prompt, defaults + project-level config."""

    # ── Metadata ──────────────────────────────────────────

    shot_id: str = ""
    """Identifier for the shot this prompt belongs to."""

    engine_versions: Dict[str, str] = field(default_factory=dict)
    """Version tags for each contributing engine (for debugging)."""

    # ── Default Lighting (shared across shots) ─────────────

    DEFAULT_LIGHTING: str = (
        "电影级光影，柔和体积光，自然色温，"
        "高动态范围，细节阴影，边缘光"
    )

    DEFAULT_NEGATIVE: str = (
        "低质量，模糊，变形，丑陋，多余肢体，"
        "水印，文字，签名，裁剪不当，比例失调，"
        "曝光过度，曝光不足"
    )

    # ── Synthesis Methods ─────────────────────────────────

    def to_flux_prompt(self) -> str:
        """Synthesize all dimensions into a Flux image generation prompt.

        Priority order: character > scene > camera > lighting > emotion > motion.

        Returns:
            Complete Flux prompt string.
        """
        parts: List[str] = []

        # Quality prefix
        parts.append("masterpiece, best quality")

        # Character (highest priority)
        if self.character_prompt:
            parts.append(self.character_prompt)

        # Scene (as backdrop)
        if self.scene_prompt:
            parts.append(f"({self.scene_prompt}:1.1)")

        # Camera
        if self.camera_prompt:
            parts.append(self.camera_prompt)

        # Emotion
        if self.emotion_prompt:
            parts.append(self.emotion_prompt)

        # Motion (lower weight for static image)
        if self.motion_prompt:
            parts.append(f"({self.motion_prompt}:0.8)")

        # Lighting
        if self.lighting_prompt:
            parts.append(self.lighting_prompt)
        else:
            parts.append(self.DEFAULT_LIGHTING)

        return ", ".join(parts)

    def to_wan_prompt(self) -> str:
        """Synthesize all dimensions into a Wan I2V video generation prompt.

        Focus on motion and temporal continuity.

        Returns:
            Complete Wan video prompt string.
        """
        parts: List[str] = []

        # Starting frame reference
        parts.append("起始帧参考上一分镜")

        # Character with motion
        if self.character_prompt and self.motion_prompt:
            parts.append(f"{self.character_prompt}，{self.motion_prompt}")
        elif self.character_prompt:
            parts.append(self.character_prompt)
        elif self.motion_prompt:
            parts.append(self.motion_prompt)

        # Camera movement
        if self.camera_prompt:
            parts.append(self.camera_prompt)

        # Emotion continuity
        if self.emotion_prompt:
            parts.append(self.emotion_prompt)

        # Scene backdrop
        if self.scene_prompt:
            parts.append(f"背景：{self.scene_prompt}")

        # Quality tags
        parts.append("动漫风格，逼真精细，60fps流畅动画")

        return "。".join(parts) + "。"

    def to_json(self) -> dict:
        """Serialize to JSON-compatible dict.

        Returns:
            Dict with all 7 dimensions and metadata.
        """
        return {
            "shot_id": self.shot_id,
            "character_prompt": self.character_prompt,
            "scene_prompt": self.scene_prompt,
            "camera_prompt": self.camera_prompt,
            "emotion_prompt": self.emotion_prompt,
            "motion_prompt": self.motion_prompt,
            "lighting_prompt": self.lighting_prompt,
            "negative_prompt": self.negative_prompt,
            "engine_versions": self.engine_versions,
        }

    @classmethod
    def from_json(cls, data: dict) -> "PromptV35":
        """Deserialize from JSON dict.

        Args:
            data: Dict with prompt dimension fields.

        Returns:
            PromptV35 instance.
        """
        return cls(
            shot_id=data.get("shot_id", ""),
            character_prompt=data.get("character_prompt", ""),
            scene_prompt=data.get("scene_prompt", ""),
            camera_prompt=data.get("camera_prompt", ""),
            emotion_prompt=data.get("emotion_prompt", ""),
            motion_prompt=data.get("motion_prompt", ""),
            lighting_prompt=data.get("lighting_prompt", ""),
            negative_prompt=data.get("negative_prompt", ""),
            engine_versions=data.get("engine_versions", {}),
        )

    # ── V3.0 Backward Compatibility ───────────────────────

    def to_legacy_dict(self) -> Dict[str, str]:
        """Convert to V3.0 single-field format for backward compatibility.

        Returns:
            Dict with 'prompt' key containing synthesized Flux prompt.
        """
        return {"prompt": self.to_flux_prompt()}

    def is_empty(self) -> bool:
        """Check if all dimensions are empty."""
        return not any([
            self.character_prompt,
            self.scene_prompt,
            self.camera_prompt,
            self.emotion_prompt,
            self.motion_prompt,
        ])


# ============================================================
# V3.5 Prompt Engine
# ============================================================

class PromptEngine:
    """V3.5 Prompt Engine — orchestrates 7-dimension prompt assembly.

    Accepts outputs from all AI Engines and produces PromptV35.
    Backward compatible with V3.0 via to_legacy_dict().

    Usage:
        engine = PromptEngine()
        prompt = engine.assemble(
            character_prompt=char_reasoner_output,
            scene_prompt=scene_reasoner_output,
            camera_prompt=camera_plan,
            motion_prompt=motion_plan,
            emotion_prompt=emotion_data,
        )
        flux_prompt = prompt.to_flux_prompt()
        wan_prompt = prompt.to_wan_prompt()
    """

    def __init__(self, default_lighting: str = "", default_negative: str = "") -> None:
        """Initialize Prompt Engine.

        Args:
            default_lighting: Override default lighting prompt.
            default_negative: Override default negative prompt.
        """
        self._default_lighting = default_lighting or PromptV35.DEFAULT_LIGHTING
        self._default_negative = default_negative or PromptV35.DEFAULT_NEGATIVE
        logger.info("PromptEngine V3.5 initialized")

    # ── Main assembly method ──────────────────────────────

    def assemble(
        self,
        shot_id: str = "",
        character_prompt: str = "",
        scene_prompt: str = "",
        camera_prompt: str = "",
        emotion_prompt: str = "",
        motion_prompt: str = "",
        lighting_prompt: str = "",
        negative_prompt: str = "",
        engine_versions: Optional[Dict[str, str]] = None,
    ) -> PromptV35:
        """Assemble a 7-dimensional prompt from engine outputs.

        Args:
            shot_id: Shot identifier.
            character_prompt: From CharacterReasoner.
            scene_prompt: From SceneReasoner.
            camera_prompt: From CameraPlanner.
            emotion_prompt: From DialogueOptimizer.
            motion_prompt: From MotionPlanner.
            lighting_prompt: Custom lighting (uses default if empty).
            negative_prompt: Custom negative (uses default if empty).
            engine_versions: Version tags for debugging.

        Returns:
            Complete PromptV35 with all dimensions filled.
        """
        prompt = PromptV35(
            shot_id=shot_id,
            character_prompt=character_prompt,
            scene_prompt=scene_prompt,
            camera_prompt=camera_prompt,
            emotion_prompt=emotion_prompt,
            motion_prompt=motion_prompt,
            lighting_prompt=lighting_prompt or self._default_lighting,
            negative_prompt=negative_prompt or self._default_negative,
            engine_versions=engine_versions or {},
        )

        logger.debug(
            f"PromptEngine: assembled prompt for shot {shot_id}, "
            f"dimensions filled: {sum(1 for v in [
                character_prompt, scene_prompt, camera_prompt,
                emotion_prompt, motion_prompt
            ] if v)}/5"
        )
        return prompt

    def assemble_from_engines(
        self,
        shot_data: Dict[str, Any],
        character_output: Optional[str] = None,
        scene_output: Optional[str] = None,
        camera_config: Optional[Dict[str, Any]] = None,
        motion_plan: Optional[Dict[str, Any]] = None,
        emotion_data: Optional[Dict[str, Any]] = None,
    ) -> PromptV35:
        """Convenience method: assemble from structured engine outputs.

        Args:
            shot_data: Core shot data with shot_id, action, scene, etc.
            character_output: Character prompt text.
            scene_output: Scene prompt text.
            camera_config: CameraPlanner output dict.
            motion_plan: MotionPlanner output dict.
            emotion_data: DialogueOptimizer output dict.

        Returns:
            PromptV35.
        """
        shot_id = shot_data.get("shot_id", "")

        # Extract text from structured engine outputs
        character_prompt = character_output or ""

        scene_prompt = scene_output or ""

        camera_prompt = ""
        if camera_config:
            shot_type = camera_config.get("shot_type", "")
            cam_movement = camera_config.get("camera_movement", "")
            depth = camera_config.get("depth_of_field", "")
            cam_parts = [p for p in [shot_type, cam_movement, depth] if p]
            camera_prompt = "，".join(cam_parts)

        motion_prompt = ""
        if motion_plan:
            motion_parts = []
            for key in ["body_motion", "facial_motion", "camera_micro_motion"]:
                val = motion_plan.get(key, "")
                if val:
                    motion_parts.append(val)
            motion_prompt = "。".join(motion_parts)

        emotion_prompt = ""
        if emotion_data:
            emotion_prompt = emotion_data.get("dominant_emotion", "")

        return self.assemble(
            shot_id=shot_id,
            character_prompt=character_prompt,
            scene_prompt=scene_prompt,
            camera_prompt=camera_prompt,
            emotion_prompt=emotion_prompt,
            motion_prompt=motion_prompt,
        )

    # ── Batch assembly ────────────────────────────────────

    def assemble_batch(
        self,
        shots: List[Dict[str, Any]],
        character_prompts: Optional[List[str]] = None,
        scene_prompts: Optional[List[str]] = None,
        camera_configs: Optional[List[Dict[str, Any]]] = None,
        motion_plans: Optional[List[Dict[str, Any]]] = None,
        emotion_data_list: Optional[List[Dict[str, Any]]] = None,
    ) -> List[PromptV35]:
        """Assemble prompts for a batch of shots.

        Args:
            shots: List of shot data dicts.
            character_prompts: Per-shot character prompts.
            scene_prompts: Per-shot scene prompts.
            camera_configs: Per-shot camera configs.
            motion_plans: Per-shot motion plans.
            emotion_data_list: Per-shot emotion data.

        Returns:
            List of PromptV35, one per shot.
        """
        count = len(shots)
        results: List[PromptV35] = []

        for i in range(count):
            prompt = self.assemble_from_engines(
                shot_data=shots[i],
                character_output=character_prompts[i] if character_prompts and i < len(character_prompts) else None,
                scene_output=scene_prompts[i] if scene_prompts and i < len(scene_prompts) else None,
                camera_config=camera_configs[i] if camera_configs and i < len(camera_configs) else None,
                motion_plan=motion_plans[i] if motion_plans and i < len(motion_plans) else None,
                emotion_data=emotion_data_list[i] if emotion_data_list and i < len(emotion_data_list) else None,
            )
            results.append(prompt)

        logger.info(f"PromptEngine: assembled {len(results)} batch prompts")
        return results

    # ── Utility ───────────────────────────────────────────

    def make_legacy(self, prompt: PromptV35) -> Dict[str, str]:
        """Convert V3.5 prompt to V3.0 format for pipeline compatibility.

        Args:
            prompt: V3.5 PromptV35 instance.

        Returns:
            V3.0-compatible dict with 'prompt' key.
        """
        return prompt.to_legacy_dict()

    def to_json_string(self, prompt: PromptV35, indent: int = 2) -> str:
        """Serialize prompt to JSON string.

        Args:
            prompt: PromptV35 instance.
            indent: JSON indentation.

        Returns:
            JSON string.
        """
        return json.dumps(prompt.to_json(), ensure_ascii=False, indent=indent)


# ============================================================
# V3.0 Backward Compatibility Alias
# ============================================================

# For code that imports PromptEngine expecting V3.0 behavior,
# the to_legacy_dict() and make_legacy() methods provide the
# V3.0 single-field output format.
